using KmOcr.Domain.Common;

namespace KmOcr.Domain.Documents;

/// <summary>
/// Stores AI extraction output for a processed document.
/// </summary>
public sealed class AiExtraction : Entity
{
    /// <summary>
    /// Creates an empty AI extraction row for Entity Framework.
    /// </summary>
    private AiExtraction()
    {
        Classification = string.Empty;
        Summary = string.Empty;
        ExtractedEntitiesJson = "{}";
        Engine = string.Empty;
    }

    /// <summary>
    /// Creates an AI extraction result for a document.
    /// </summary>
    private AiExtraction(Guid documentId, string classification, string summary, string extractedEntitiesJson, decimal confidenceScore, string engine)
    {
        DocumentId = documentId;
        Classification = RequireText(classification, nameof(classification));
        Summary = RequireText(summary, nameof(summary));
        ExtractedEntitiesJson = RequireText(extractedEntitiesJson, nameof(extractedEntitiesJson));
        ConfidenceScore = confidenceScore;
        Engine = RequireText(engine, nameof(engine));
    }

    /// <summary>
    /// Gets the owning document identifier.
    /// </summary>
    public Guid DocumentId { get; private set; }

    /// <summary>
    /// Gets the document classification predicted by AI.
    /// </summary>
    public string Classification { get; private set; }

    /// <summary>
    /// Gets the document summary generated by AI.
    /// </summary>
    public string Summary { get; private set; }

    /// <summary>
    /// Gets extracted entities as JSON.
    /// </summary>
    public string ExtractedEntitiesJson { get; private set; }

    /// <summary>
    /// Gets AI confidence score between 0 and 1.
    /// </summary>
    public decimal ConfidenceScore { get; private set; }

    /// <summary>
    /// Gets the AI engine name.
    /// </summary>
    public string Engine { get; private set; }

    /// <summary>
    /// Creates a validated AI extraction result.
    /// </summary>
    public static AiExtraction Create(Guid documentId, string classification, string summary, string extractedEntitiesJson, decimal confidenceScore, string engine)
    {
        ValidateConfidence(confidenceScore);
        return new AiExtraction(documentId, classification, summary, extractedEntitiesJson, confidenceScore, engine);
    }

    /// <summary>
    /// Replaces AI extraction output for a reprocessed document.
    /// </summary>
    public void Update(string classification, string summary, string extractedEntitiesJson, decimal confidenceScore, string engine)
    {
        ValidateConfidence(confidenceScore);
        Classification = RequireText(classification, nameof(classification));
        Summary = RequireText(summary, nameof(summary));
        ExtractedEntitiesJson = RequireText(extractedEntitiesJson, nameof(extractedEntitiesJson));
        ConfidenceScore = confidenceScore;
        Engine = RequireText(engine, nameof(engine));
        Touch();
    }

    /// <summary>
    /// Validates confidence range.
    /// </summary>
    private static void ValidateConfidence(decimal confidenceScore)
    {
        if (confidenceScore is < 0 or > 1)
        {
            throw new ArgumentOutOfRangeException(nameof(confidenceScore), "Confidence score must be between 0 and 1.");
        }
    }

    /// <summary>
    /// Validates required text and returns the trimmed value.
    /// </summary>
    private static string RequireText(string value, string parameterName)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException("Value is required.", parameterName);
        }

        return value.Trim();
    }
}
